---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: 0c611b3c-3e12-4e16-8255-6c618e125385
    azure.workload.identity/tenant-id: 7a51efba-4cd4-4200-aea4-df68900aeac1
  labels:
    app.kubernetes.io/component: identity
    app.kubernetes.io/name: nucleus-indexer
    app.kubernetes.io/part-of: bookstore-agents
  name: nucleus-indexer
  namespace: nucleus
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: 890700b0-298a-4de7-88b8-20b83eb80ba5
    azure.workload.identity/tenant-id: 7a51efba-4cd4-4200-aea4-df68900aeac1
  labels:
    app.kubernetes.io/component: identity
    app.kubernetes.io/name: nucleus-runtime
    app.kubernetes.io/part-of: bookstore-agents
  name: nucleus-runtime
  namespace: nucleus
