---
apiVersion: v1
kind: Service
metadata:
  name: customer-concierge-agent
  labels:
    app.kubernetes.io/name: customer-concierge-agent
    app.kubernetes.io/component: agent
    app.kubernetes.io/part-of: bookstore-agents
spec:
  ports:
  - name: http
    port: 8201
    targetPort: http
  selector:
    app.kubernetes.io/name: customer-concierge-agent
