---
apiVersion: v1
kind: Service
metadata:
  name: message-drafter-agent
  labels:
    app.kubernetes.io/name: message-drafter-agent
    app.kubernetes.io/component: agent
    app.kubernetes.io/part-of: bookstore-agents
spec:
  ports:
  - name: http
    port: 8205
    targetPort: http
  selector:
    app.kubernetes.io/name: message-drafter-agent
