variable "app_name" {
  description = "Short workload/application name used in every Azure resource name."
  type        = string

  validation {
    condition     = can(regex("^[a-z0-9]+$", var.app_name))
    error_message = "app_name must contain only lowercase letters and numbers."
  }
}

variable "environment" {
  description = "Deployment environment code."
  type        = string

  validation {
    condition     = contains(["dev", "test", "stg", "prod"], var.environment)
    error_message = "environment must be one of dev, test, stg, or prod."
  }
}

variable "location" {
  description = "Azure region display name."
  type        = string
}

variable "region_code" {
  description = "Short region code used in resource names."
  type        = string

  validation {
    condition     = can(regex("^[a-z0-9]+$", var.region_code))
    error_message = "region_code must contain only lowercase letters and numbers."
  }
}

variable "instance" {
  description = "Three-digit instance number for the primary resource of each type."
  type        = string
  default     = "001"

  validation {
    condition     = can(regex("^[0-9]{3}$", var.instance))
    error_message = "instance must be a three-digit string such as 001."
  }
}

variable "node_resource_group_instance" {
  description = "Three-digit instance number for the AKS-managed node resource group."
  type        = string
  default     = "002"

  validation {
    condition     = can(regex("^[0-9]{3}$", var.node_resource_group_instance))
    error_message = "node_resource_group_instance must be a three-digit string such as 002."
  }
}

variable "tags" {
  description = "Additional tags merged with the mandatory workload tags."
  type        = map(string)
  default     = {}
}

variable "aks_kubernetes_version" {
  description = "Optional AKS Kubernetes version. Null lets Azure select the regional default."
  type        = string
  default     = null
  nullable    = true
}

variable "aks_node_vm_size" {
  description = "VM size for the lightweight AKS system node pool."
  type        = string
  default     = "Standard_D4ds_v5"
}

variable "aks_node_min_count" {
  description = "Minimum node count for the AKS system node pool."
  type        = number
  default     = 1
}

variable "aks_node_max_count" {
  description = "Maximum node count for the AKS system node pool."
  type        = number
  default     = 3
}

variable "aks_api_server_authorized_ip_ranges" {
  description = "CIDRs allowed to reach the public AKS API. Empty means unrestricted public access for the initial dev phase."
  type        = list(string)
  default     = []
}

variable "kubernetes_namespace" {
  description = "Kubernetes namespace used by the application service accounts."
  type        = string
  default     = "nucleus"
}

variable "runtime_service_account_name" {
  description = "Kubernetes service account federated to the runtime managed identity."
  type        = string
  default     = "nucleus-runtime"
}

variable "indexer_service_account_name" {
  description = "Kubernetes service account federated to the indexing managed identity."
  type        = string
  default     = "nucleus-indexer"
}

variable "postgresql_version" {
  description = "PostgreSQL major version for Azure Database for PostgreSQL Flexible Server."
  type        = string
  default     = "16"
}

variable "postgresql_sku_name" {
  description = "Compute SKU for the development PostgreSQL Flexible Server."
  type        = string
  default     = "B_Standard_B2ms"
}

variable "postgresql_storage_mb" {
  description = "Provisioned PostgreSQL storage in MiB."
  type        = number
  default     = 32768
}

variable "postgresql_admin_username" {
  description = "PostgreSQL server administrator login. The password is generated by Terraform."
  type        = string
  default     = "nucleusadmin"
}

variable "postgresql_operator_firewall_rules" {
  description = "Optional public IPv4 ranges allowed to connect directly to PostgreSQL."
  type = map(object({
    start_ip_address = string
    end_ip_address   = string
  }))
  default = {}
}

variable "search_sku" {
  description = "Azure AI Search SKU."
  type        = string
  default     = "basic"
}

variable "foundry_model_name" {
  description = "Microsoft Foundry model catalog name to deploy."
  type        = string
}

variable "foundry_model_version" {
  description = "Microsoft Foundry model version to deploy."
  type        = string
}

variable "foundry_model_sku_name" {
  description = "Microsoft Foundry model deployment SKU."
  type        = string
  default     = "DataZoneStandard"
}

variable "foundry_model_capacity" {
  description = "Model deployment capacity in provider-specific capacity units."
  type        = number
  default     = 1
}

variable "log_analytics_retention_days" {
  description = "Log Analytics retention period for the initial environment."
  type        = number
  default     = 30
}
